CREATE TABLE IF NOT EXISTS apps
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_apps PRIMARY KEY (id),
    CONSTRAINT apps_unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id     BIGINT                                  NOT NULL,
    uri        VARCHAR(2048),
    ip         VARCHAR(15)                             NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id),
    CONSTRAINT fk_hit_on_apps FOREIGN KEY (app_id) REFERENCES apps (id)
);
